"""Pattern thresholds for HarnessCI session autopsy analysis."""

THRASHING_MIN_EDIT_ATTEMPTS = 8
THRASHING_MIN_FAIL_RATIO = 0.5

CONTEXT_GAP_MIN_LATENCY_MS = 1_800_000
CONTEXT_GAP_MAX_CHURN = 50

INEFFICIENCY_MIN_TOKENS_PER_LINE = 500
INEFFICIENCY_MIN_TOKENS = 10_000

SCOPE_CREEP_MIN_RETRIES = 3
SCOPE_CREEP_MIN_FILES_CHANGED = 8

DEFAULT_COST_PER_TOKEN = 0.000015
